// ─── Shared utilities ─────────────────────────────────────────────────────────
export function rand(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
export function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
export function fmt(n: number) {
  return n >= 1000000
    ? `${(n / 1000000).toFixed(1)}M`
    : n >= 1000
    ? `${(n / 1000).toFixed(0)}K`
    : `${n}`;
}

// ─── Writing Studio ───────────────────────────────────────────────────────────
export function generateWritingStudio(topic: string, format: string, tone: string): string {
  const t = topic || "content creation";
  const yr = new Date().getFullYear();

  if (format === "Blog Post") {
    return `# ${t.split(" ").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}: The Complete Guide for ${yr}

*${rand(8, 15)} min read · ${fmt(rand(1, 8) * 1000)} potential readers*

---

## Introduction

Most people approach ${t} completely wrong. They spend hours on tactics that stopped working years ago, while a small group of creators quietly builds an audience using a completely different system.

In this guide, I'm going to show you exactly what that system looks like — and how you can start using it today.

---

## The Problem with Conventional ${t.charAt(0).toUpperCase() + t.slice(1)} Advice

Every week, thousands of new articles get published about ${t}. They all say the same things:
- "Post consistently"
- "Engage with your audience"  
- "Use the right hashtags"

And while none of this is wrong, it misses the actual driver of growth in ${yr}: **relevance over volume**.

---

## The Framework That Actually Works

After analyzing ${fmt(rand(500, 2000))} successful creators in this space, we identified a repeatable 3-part system:

### Step 1: The Relevance Filter
Before creating any ${t} content, run it through three questions:
1. Does this solve a problem my audience has right now?
2. Would someone share this without being asked?
3. Does this reinforce my specific expertise?

If you can't answer yes to all three, rethink the concept.

### Step 2: The Authority Stack
Build credibility through specificity. Instead of "here's how to do ${t}", say "here's how I grew from ${rand(0, 500)} to ${fmt(rand(5, 50) * 1000)} using this exact ${t} approach."

Numbers, timelines, and personal results outperform generic advice by ${rand(3, 8)}× in engagement.

### Step 3: The Distribution Loop
Content that doesn't get distributed is content that doesn't exist. For every piece you create:
→ Repurpose into ${rand(3, 5)} micro-formats
→ Seed it in ${rand(2, 4)} communities relevant to your niche
→ Schedule ${rand(3, 7)} follow-up touchpoints over 30 days

---

## The ${t.charAt(0).toUpperCase() + t.slice(1)} Mistakes That Are Costing You

**Mistake #1: Starting too broad**
Beginners try to appeal to everyone. The highest-performing creators narrow their focus to one specific person and one specific problem.

**Mistake #2: Optimizing for vanity metrics**
Likes and followers feel good. Revenue, email signups, and inbound opportunities are what actually matter.

**Mistake #3: Inconsistent voice**
Your audience follows you, not your topic. Personality and POV are your moat.

---

## Action Plan: Your First 30 Days

| Week | Focus | Output |
|------|-------|--------|
| 1 | Research + niche validation | 3 audience interviews |
| 2 | Foundation content | 5 cornerstone pieces |
| 3 | Distribution test | 3 channels × 5 posts |
| 4 | Analyze + double down | 1 winning format identified |

---

## Conclusion

${t.charAt(0).toUpperCase() + t.slice(1)} in ${yr} rewards creators who are specific, consistent, and genuinely helpful. Start with the framework above, measure what works, and cut everything else.

The creators winning right now aren't doing more — they're doing less, better.

---
*Generated by CreatorOS Writing Studio · ${new Date().toLocaleDateString()}*`;
  }

  if (format === "Twitter Thread") {
    const points = rand(7, 12);
    const pointsArr = Array.from({ length: points }, (_, i) => `${i + 2}/ ${pick([
      `Most people skip this step with ${t}. Don't. It's the difference between ${rand(100, 999)} and ${fmt(rand(10, 100) * 1000)} views.`,
      `The ${t} rule nobody talks about: quality of distribution > quality of content. Your best post means nothing if ${rand(1, 5)} people see it.`,
      `I tested ${rand(20, 50)} different ${t} approaches last year. The winner was the one I almost didn't try.`,
      `${t.charAt(0).toUpperCase() + t.slice(1)} tip: spend ${rand(20, 40)}% of your time creating, ${rand(60, 80)}% distributing. Most creators do the opposite.`,
      `The fastest way to grow with ${t}: document your process publicly. Audiences don't just want results — they want the journey.`,
      `Unpopular take: your ${t} strategy should bore you. Boring + consistent beats exciting + sporadic every time.`,
      `What separates top 1% ${t} creators from everyone else? They know exactly who they're talking to. Not "everyone." One specific person.`,
      `The ${t} metric that actually predicts success: saves. Not likes, not comments — saves. Track them obsessively.`,
      `${t.charAt(0).toUpperCase() + t.slice(1)} insight: your first ${rand(50, 200)} posts are tuition. Stop expecting them to go viral. Pay attention to what resonates and build on it.`,
    ])}`)
    return `🧵 ${t.charAt(0).toUpperCase() + t.slice(1)}: a thread

1/ I've studied ${fmt(rand(100, 1000))} creators who built their audience with ${t}. Here's the framework that separates the top ${rand(1, 5)}% from everyone else:

${pointsArr.join("\n\n")}

${points + 2}/ The summary:
→ Pick one niche and go deep
→ Distribute more than you create
→ Document, don't just produce
→ Measure saves, not vanity metrics
→ Stay consistent for ${rand(6, 18)} months before judging results

${points + 3}/ If this helped, retweet the first tweet so others can find it.

And follow me for more ${t} breakdowns every week.

---
*Generated by CreatorOS Writing Studio*`;
  }

  if (format === "Newsletter") {
    return `Subject: The ${t} strategy that changed everything for me

---

Hey [First Name],

Something clicked for me recently about ${t} — and I had to share it immediately.

**The insight:** ${pick([
  "Volume is a trap. The creators winning right now post less, but every post is engineered to convert.",
  "Authenticity outperforms strategy. The most engaging content feels like a text from a friend, not a press release.",
  "Distribution is the unlock. The best content strategy in the world fails without a distribution engine behind it.",
  "Specificity is the moat. Niche down until it feels uncomfortable — that's usually the right level.",
])}

Here's what I mean:

**What most creators do**
They focus ${rand(80, 95)}% of their time on creating and ${rand(5, 20)}% on everything else. Production feels productive. It rarely is.

**What actually works in ${yr}**
The top ${t} creators I've studied spend their time roughly like this:
- ${rand(30, 45)}% creating
- ${rand(30, 45)}% distributing
- ${rand(15, 25)}% studying what worked

The shift feels counterintuitive at first. Then the results speak for themselves.

**Your action item this week**
Take your top-performing ${t} piece and repurpose it into ${rand(3, 5)} different formats. Don't create something new — amplify what already works.

If you try this, hit reply and tell me what happens. I read every response.

Talk soon,
[Your Name]

P.S. Next week I'm sharing the exact ${t} content calendar I used to grow to ${fmt(rand(10, 100) * 1000)} subscribers. Don't miss it.

---
*Generated by CreatorOS Writing Studio*`;
  }

  // LinkedIn Post
  return `📌 An uncomfortable truth about ${t}:

Most people aren't failing because of effort. They're failing because of direction.

I spent ${rand(1, 3)} years grinding at ${t} with mediocre results. Then I changed ${rand(1, 3)} things:

**1. I got obsessively specific**
Instead of targeting "anyone interested in ${t}", I narrowed my focus to one type of person with one specific problem. My reach dropped by ${rand(30, 60)}%. My conversions tripled.

**2. I stopped optimizing for impressions**
Impressions are ego. Saves, replies, and DMs are signal. I started measuring the right things.

**3. I treated ${t} like a product, not content**
Every piece I create now answers: "What does this person do differently after reading this?" If I can't answer it, I don't publish it.

The results?
→ +${rand(150, 400)}% engagement rate
→ ${fmt(rand(1, 10) * 1000)} new followers in ${rand(60, 120)} days  
→ ${rand(3, 8)} inbound collaboration requests per month

The strategy isn't new. But most people skip it because it requires patience.

Agree or disagree? Share your experience in the comments.

---
*Generated by CreatorOS Writing Studio*`;
}

// ─── Reel Generator ────────────────────────────────────────────────────────────
export function generateReel(topic: string, platform: string, duration: string): string {
  const t = topic || "your topic";
  const secs = parseInt(duration) || 30;
  const shots = Math.floor(secs / 3);

  return `## Reel Script — "${t}" (${duration} · ${platform})

**Predicted Performance:** ${fmt(rand(50, 900) * 1000)} plays · ${rand(6, 14)}% engagement · ${rand(60, 85)}% completion rate

---

### HOOK (0–${Math.min(3, secs)}s) — NON-NEGOTIABLE
> "${pick([
  `"This ${t} thing changed everything. Watch till the end."`,
  `"POV: You finally found the ${t} tutorial that actually works."`,
  `"Stop scrolling. This ${t} tip will save you hours."`,
  `"Nobody is talking about this ${t} trick. I had to share it."`,
])}"

⚡ Text overlay: Bold, high contrast, ${rand(3, 6)} words max
⚡ Start mid-action — no intro, no "hey guys"

---

### SHOT LIST (${shots} cuts total)

${Array.from({ length: Math.min(shots, 10) }, (_, i) => `**Shot ${i + 1}** (${i * Math.round(secs / shots)}s–${(i + 1) * Math.round(secs / shots)}s)
→ ${pick([
  "Close-up screen recording",
  "Face to camera — direct eye contact",
  "Over-shoulder POV shot",
  "Text animation on dark background",
  "Quick B-roll transition",
  "Side-by-side comparison",
  "Before/after reveal",
  "Step callout with arrow graphic",
])}: ${t} moment ${i + 1}`).join("\n\n")}

---

### AUDIO STRATEGY
🎵 Trending sound: Check ${platform} trending audio in your niche this week
🎤 Voice-over: Record your own — performs +${rand(20, 45)}% vs music-only
📊 ${rand(55, 70)}% of ${platform} users watch without sound — add captions

### TEXT OVERLAYS (Place at bottom third)
- Frame 1: "${t.charAt(0).toUpperCase() + t.slice(1)} hack 🔥"
- Mid-point: "${pick(["Here's how", "The secret:", "This is why:", "Watch this:"])}"
- Final frame: "Follow for more ${t} tips"

### CAPTION (Copy-ready)
${pick([
  `${t.charAt(0).toUpperCase() + t.slice(1)} tip that changed the game for me 🎯\n\nSave this so you don't forget it\n\n#${t.replace(/\s/g, "")} #viral #fyp #trending`,
  `Nobody told me this about ${t} 🤯\n\nWhich part helped you most? Comment below 👇\n\n#${t.replace(/\s/g, "")} #contentcreator #reels`,
  `POV: You just found the ${t} shortcut 📲\n\nShare with someone who needs to see this\n\n#${t.replace(/\s/g, "")} #tips #explore`,
])}

### POSTING STRATEGY
- **Best time for ${platform}:** ${pick(["6–8am", "12–2pm", "6–9pm"])} on ${pick(["Mon/Wed/Fri", "Tue/Thu/Sat", "Wed/Fri/Sun"])}
- **Reply to first ${rand(10, 20)} comments** within 1 hour of posting
- **Pin to profile** if it hits ${fmt(rand(10, 50) * 1000)} views in 24h

---
*Generated by CreatorOS Reel Generator*`;
}

export function generateReelCaption(topic: string, platform: string): string {
  const t = topic || "your topic";
  const captions = [
    `${t.charAt(0).toUpperCase() + t.slice(1)} tip that literally changed my entire approach 🔥\n\nSave this before it gets buried 📌\n\nWhat's your biggest ${t} challenge? Drop it below 👇\n\n#${t.replace(/\s+/g, "")} #viral #fyp #trending #contentcreator`,
    `Nobody talks about this ${t} method but it WORKS 🎯\n\nI wish someone showed me this earlier...\n\nShare with a creator friend who needs this!\n\n#${t.replace(/\s+/g, "")} #${platform.toLowerCase()} #reels #tips`,
    `POV: You just discovered the ${t} shortcut 😮\n\nLike if this helped, follow for more every week!\n\n${platform === "TikTok" ? "#fyp #foryoupage #tiktok" : "#reels #explore #instagram"} #${t.replace(/\s+/g, "")}`,
  ];
  return captions.join("\n\n---\n\n");
}

// ─── Thumbnail Maker ──────────────────────────────────────────────────────────
export function generateThumbnail(title: string, style: string, niche: string): string {
  const t = title || "Your Video Title";
  const n = niche || "content creation";

  const layouts: Record<string, string> = {
    Minimal: `Clean white/dark background · Single focal point · ${rand(2, 4)} word text maximum`,
    Bold: `High contrast split background · Large bold text · Strong facial expression`,
    Dark: `Dark gradient background · Neon text glow · Mysterious/premium feel`,
    Neon: `Dark background · Cyan/purple neon text · Tech/futuristic aesthetic`,
    Cinematic: `Wide letterbox crop · Film grain overlay · Movie-poster typography`,
  };

  return `## Thumbnail Design Brief — "${t}"

**CTR Prediction:** ${(rand(7, 15) / 10).toFixed(1)}% · ${rand(2, 5)}× your channel avg

---

### Style: ${style}
**Layout:** ${layouts[style] || layouts["Bold"]}

---

### TEXT ELEMENTS

**Main Headline** (largest, most readable from phone screen)
Option A: "${t}"
Option B: "${pick(["The TRUTH about", "I tested", "How I", "Why Your", "Stop doing this"])}: ${n.charAt(0).toUpperCase() + n.slice(1)}"
Option C: "${rand(3, 9)} ${n} ${pick(["secrets", "mistakes", "hacks", "tips"])}"

**Sub-text** (smaller, adds context)
"${pick(["You won't believe #3", "I wish I knew this sooner", `${rand(2025, 2026)} method`, "Nobody talks about this", "The real answer"])}"

---

### COLOR PALETTE

| Role | Color | Hex |
|------|-------|-----|
| Background | ${pick(["Deep navy", "Jet black", "Dark charcoal", "Midnight blue"])} | ${pick(["#0a0a0f", "#111118", "#0d0d1a", "#080810"])} |
| Primary text | ${pick(["Bright white", "Neon cyan", "Electric yellow", "Hot orange"])} | ${pick(["#FFFFFF", "#00D4FF", "#FFE600", "#FF6B35"])} |
| Accent | ${pick(["Neon cyan", "Electric purple", "Vibrant red", "Hot pink"])} | ${pick(["#00D4FF", "#8B5CF6", "#FF3B3B", "#FF006E"])} |
| Highlight box | Semi-transparent ${pick(["blue", "purple", "red", "orange"])} | rgba(${rand(0, 50)},${rand(100, 255)},${rand(150, 255)},0.2) |

---

### COMPOSITION GUIDE

\`\`\`
┌─────────────────────────────────┐
│  [PERSON - left third]          │  ← Face: shocked/excited expression
│                  [MAIN TEXT]    │  ← Right 2/3, large, bold
│                  [Sub text]     │  ← Below main, 40% size
│            [ACCENT ELEMENT]    │  ← Arrow, highlight box, or graphic
└─────────────────────────────────┘
\`\`\`

**Eye path:** Face → Main text → Sub text → CTA element

---

### FACE EXPRESSION GUIDE
→ **Curiosity/Shock** — eyebrows raised, mouth slightly open
→ **Point toward text** — draws viewer's eye to the title
→ **No direct camera** — looking at something off-frame increases curiosity

### FONT RECOMMENDATIONS
- Headline: **Impact, Anton, or Bebas Neue** — all caps, tight tracking
- Sub-text: **Montserrat Bold or DM Sans Bold** — high legibility
- Avoid: thin fonts, script fonts, default system fonts

---

### SPLIT TEST STRATEGY
Create 2 versions, change only 1 element:
- Version A: Face prominent + short text
- Version B: Large text + small face insert

Upload both and monitor CTR for 48h. Keep winner. Repeat monthly.

---
*Generated by CreatorOS Thumbnail Maker*`;
}

export function generateThumbnailChecklist(style: string): string {
  return `## Production Checklist — ${style} Style

### Before Export
☐ Image is exactly 1280×720px (16:9)
☐ Text is readable at 100px wide (phone thumbnail size)
☐ No important elements in the outer 10% (may get cropped)
☐ Face shows a clear, strong emotion
☐ Under ${rand(4, 6)} words of text total
☐ Contrast ratio passes accessibility check

### File Specs
- Format: JPG (not PNG — loads faster)
- File size: Under 2MB
- Color space: sRGB (not CMYK)
- Export quality: 90% or higher

### Recommended Free Tools
→ Canva — fastest for templates
→ Photopea — free Photoshop alternative  
→ Remove.bg — background removal for faces
→ Squoosh — compress final image without quality loss

### A/B Test Schedule
Week 1: Test expression vs no-face
Week 2: Test text size large vs medium
Week 3: Test color background variation
Week 4: Keep winner, archive losers

*Generated by CreatorOS Thumbnail Maker*`;
}

// ─── Website Builder ──────────────────────────────────────────────────────────
export function generateWebsite(name: string, niche: string, bio: string, style: string): string {
  const n = name || "Your Name";
  const ni = niche || "content creator";
  const styles: Record<string, string> = {
    Minimal: "Clean, whitespace-heavy, typography-focused",
    Bold: "High contrast, strong colors, confident typography",
    Dark: "Dark theme, subtle gradients, premium feel",
    Neon: "Dark + neon accents, futuristic, tech-forward",
  };

  return `## Creator Portfolio — ${n}

**Style:** ${style} · ${styles[style] || "Minimal"}
**Estimated build time:** ${rand(25, 55)} minutes with a page builder

---

### HERO SECTION

**Headline:** "${pick([
  `I help ${ni} creators build audiences that actually convert.`,
  `${n} — The ${ni} creator helping you grow faster.`,
  `${ni.charAt(0).toUpperCase() + ni.slice(1)} content that stops the scroll and starts the conversation.`,
  `Turn your ${ni} expertise into content people can't stop watching.`,
])}"

**Sub-headline:** "${bio || `${ni} creator · ${fmt(rand(5, 100) * 1000)} followers · ${rand(3, 8)} years of experience`}"

**Primary CTA:** "${pick(["Work With Me", "Watch My Content", "Download Free Guide", "Join My Community", "See My Work"])}"
**Secondary CTA:** "${pick(["Watch my latest video", "Read my newsletter", "Follow on Instagram", "See case studies"])}"

---

### ABOUT SECTION

**Section Title:** "Hi, I'm ${n}"

**Body Copy:**
"I started creating content about ${ni} because ${pick([
  "I couldn't find the kind of help I needed when I was starting out.",
  "I had knowledge that wasn't being shared in a way that actually helped people.",
  "I wanted to build something that combined my passion with real value for others.",
])}

Today, I help ${pick(["aspiring creators", "busy professionals", "ambitious entrepreneurs", "passionate beginners"])} ${pick([
  `build their ${ni} presence from scratch`,
  `grow their audience without burning out`,
  `turn their expertise into consistent content`,
  `get results with their ${ni} strategy`,
])}.

When I'm not creating, you'll find me ${pick(["exploring new tools", "reading about trends", "connecting with other creators", "testing new strategies"])}."

---

### SERVICES / OFFERS SECTION

**Option 1 — Free:** "${pick(["Free Guide", "Content Calendar Template", "Starter Toolkit", "Mini Course"])} — ${pick(["Get instant access", "Download now", "Start here", "Free forever"])}"

**Option 2 — Entry:** "${pick(["Workshop", "Starter Pack", "Masterclass", "Templates Bundle"])} — $${rand(27, 97)}"

**Option 3 — Core:** "${pick(["Course", "Program", "Accelerator", "Bootcamp"])} — $${rand(197, 497)}"

**Option 4 — Premium:** "${pick(["1:1 Coaching", "Done-With-You", "VIP Day", "Mentorship"])} — $${fmt(rand(1, 5) * 1000)}"

---

### SOCIAL PROOF SECTION

**Stats to feature:**
→ ${fmt(rand(5, 500) * 1000)} total followers across platforms
→ ${fmt(rand(10, 200) * 1000)} email subscribers
→ ${rand(50, 500)}+ students/clients helped
→ ${rand(3, 12)}M+ content views

**Testimonial formula:**
"[Specific result] in [timeframe]. I [what changed]. — [Name, Title]"

---

### FEATURED CONTENT SECTION

Show ${rand(3, 6)} recent pieces in a grid:
- Thumbnail + title + view count
- Link to platform or embed

---

### CONTACT / COLLAB SECTION

**Headline:** "Let's work together"
**Sub:** "Open to brand partnerships, speaking, and consulting in the ${ni} space."
**Form fields:** Name · Email · Budget range · Message
**Response time:** "I reply within ${rand(24, 72)} hours"

---

### FOOTER
Links: About · Content · Services · Newsletter · [Social icons]
Legal: Privacy Policy · © ${new Date().getFullYear()} ${n}

---

### RECOMMENDED BUILDERS
→ **Framer** — Best for creators, no-code, fast
→ **Squarespace** — Best templates out of the box
→ **Webflow** — Most control, steeper learning curve
→ **Carrd** — Fastest single-page site, under 5 min

---
*Generated by CreatorOS Website Builder*`;
}

// ─── Caption Generator ────────────────────────────────────────────────────────
export function generateCaptions(description: string, tone: string): string {
  const d = description || "my latest content";
  const toneAdj = { Casual: "conversational", Professional: "authoritative", Inspirational: "uplifting", Humorous: "witty" }[tone] || "engaging";

  return `## Multi-Platform Captions — "${d}"

**Tone:** ${tone} (${toneAdj}) · Optimized for ${new Date().toLocaleString("default", { month: "long", year: "numeric" })}

---

### INSTAGRAM (${rand(150, 220)} chars + hashtags)
> ${pick([
  `${d.charAt(0).toUpperCase() + d.slice(1)} hit different when you actually understand the why behind it 💡\n\nSave this for when you need it most.\n\nWhat's your take? Drop it below 👇`,
  `Not gonna lie — this one surprised me.\n\n${d.charAt(0).toUpperCase() + d.slice(1)} isn't what most people think it is.\n\nLike if this resonated. More like this every week. 🙌`,
  `The thing about ${d} that nobody talks about:\n\nIt compounds. Slowly, then all at once.\n\nDrop ✅ in the comments if you needed to hear this.`,
])}

Hashtags: #${d.replace(/\s+/g,"").slice(0,15)} #contentcreator #${pick(["instagram","reels","explore"])} #viral #fyp #trending

---

### TIKTOK (punchy, ${rand(80, 120)} chars)
> ${pick([
  `${d.charAt(0).toUpperCase() + d.slice(1)} tip nobody told me about 🤯 Save before this gets buried`,
  `POV: You finally figured out ${d} 📲 Follow for more like this`,
  `${d.charAt(0).toUpperCase() + d.slice(1)} secret that changed everything for me 🔥 Who needed this?`,
])}

---

### YOUTUBE (SEO-optimized description)
> ${d.charAt(0).toUpperCase() + d.slice(1)} — complete breakdown in this video.

In this video, I cover:
→ Why most people get ${d} wrong
→ The ${rand(3, 5)}-step approach that actually works
→ Real examples + step-by-step walkthrough
→ Common mistakes to avoid

⏱️ Chapters:
00:00 Intro
01:${rand(10, 45)} The problem with ${d}
${rand(3, 5)}:${rand(10, 55)} The framework
${rand(6, 8)}:${rand(10, 55)} Live demo
${rand(9, 12)}:${rand(10, 55)} Key takeaways

🔔 Subscribe for more ${d} content every week.

Tags: ${d} tutorial, ${d} tips ${new Date().getFullYear()}, how to ${d}, ${d} for beginners

---

### TWITTER / X (under 280 chars)
> ${pick([
  `${d.charAt(0).toUpperCase() + d.slice(1)} tip that took me too long to learn:\n\n[Your insight here]\n\nRetweet if this helped.`,
  `Hot take: ${d} is easier than everyone makes it seem.\n\nThe hard part isn't the skill — it's the consistency.\n\nAgree?`,
  `Things I wish I knew about ${d} before I started:\n\n1. [Insight]\n2. [Insight]\n3. [The big one]\n\nWhat would you add?`,
])}

---

### LINKEDIN (professional, ${rand(200, 400)} chars)
> ${pick([
  `${d.charAt(0).toUpperCase() + d.slice(1)} taught me more about my industry than ${rand(3, 7)} years of traditional experience.\n\nHere's why: [Your unique professional insight]\n\nWhat has ${d} changed about how you work?`,
  `A lesson from ${d} that applies to every professional:\n\n[Your insight]\n\nThe best skills transfer. This one does.\n\nThoughts? Drop them below.`,
])}

---
*Generated by CreatorOS Caption Generator*`;
}

export function generateCaptionHashtags(description: string): string {
  const d = (description || "content").toLowerCase().replace(/\s+/g, "");
  return `## Hashtag Sets for "${description || "your content"}"

### Instagram (use 10–15)
**Tier 1 — Niche:** #${d} #${d}tips #${d}strategy #${d}creator #${d}hack
**Tier 2 — Category:** #contentcreator #creatoreconomy #digitalcreator #socialmediatips #contentstrategy
**Tier 3 — Reach:** #viral #fyp #trending #explore #reels

### TikTok (use 3–5)
#${d} #fyp #foryoupage #${d}tiktok #${pick(["viral","trending","foryou","tiktoktrend"])}

### YouTube Tags (in description)
${description} tutorial, ${description} tips ${new Date().getFullYear()}, how to ${description}, ${description} for beginners, best ${description}

*Generated by CreatorOS Caption Generator*`;
}

// ─── Viral Hooks Generator ────────────────────────────────────────────────────
export function generateHooks(topic: string, niche: string, count: number): string {
  const t = topic || "your topic";
  const n = niche || "content creation";
  const types = [
    "Curiosity Gap", "Pattern Interrupt", "Social Proof", "Pain Point",
    "Controversy", "Challenge", "FOMO", "Transformation", "Bold Claim", "Confession",
    "Question", "Contrarian", "Empathy", "Urgency",
  ];
  const hooks = [
    `"I tried every ${t} strategy for ${rand(30, 180)} days. Only 1 actually worked."`,
    `"The ${t} tip that took me from ${rand(0, 500)} to ${fmt(rand(10, 100) * 1000)} in ${rand(30, 90)} days."`,
    `"Most ${n} creators quit ${t} before they discover this. Don't be one of them."`,
    `"I was doing ${t} completely wrong for ${rand(1, 4)} years. Here's what I wish I knew."`,
    `"What nobody tells you about ${t} (because it makes them look bad)."`,
    `"Unpopular opinion: the best ${t} strategy is the one that bores you."`,
    `"I almost quit ${n} because of ${t}. Then I found the one thing that changed everything."`,
    `"The ${t} secret that the top ${rand(1, 5)}% of ${n} creators never share publicly."`,
    `"Stop everything. This ${t} change is the most important shift in ${new Date().getFullYear()}."`,
    `"If you're struggling with ${t}, you're not doing it wrong — you're doing the wrong thing."`,
    `"This ${t} mistake is silently killing your growth. I see it in ${rand(70, 95)}% of ${n} accounts."`,
    `"I paid $${rand(500, 5000)} to learn this ${t} lesson. Here it is for free."`,
    `"The algorithm is actively rewarding this specific ${t} approach right now. Here's how."`,
    `"After ${rand(100, 1000)} ${t} tests, I found the only ${rand(3, 5)} things that actually matter."`,
  ];

  const selected = hooks.slice(0, count).map((h, i) => (
    `**Hook ${i + 1}** *(${types[i % types.length]})*\n${h}\n\n**Why it works:** ${pick([
      `Creates a curiosity gap — viewer must watch to close the loop`,
      `Leads with a specific result — specificity builds credibility`,
      `Triggers loss aversion — "don't be one of them" activates FOMO`,
      `Confession format disarms skepticism and feels authentic`,
      `Contrarian take creates immediate disagreement or agreement — both drive engagement`,
      `Pain acknowledgment before the solution — audience feels seen`,
      `Social proof via implied expertise — establishes authority instantly`,
    ])}`
  ));

  return `## ${count} Viral Hooks — ${t} · ${n}

**Hook Score:** ${rand(88, 97)}/100 · Optimized for ${new Date().getFullYear()}

---

${selected.join("\n\n---\n\n")}

---

## Hook Psychology Matrix

| Type | Best Platform | Avg CTR Lift | Best For |
|------|--------------|--------------|----------|
| Curiosity Gap | All | +${rand(25, 45)}% | Cold audiences |
| Pain Point | Instagram/TikTok | +${rand(20, 40)}% | Warm audiences |
| Social Proof | YouTube | +${rand(15, 35)}% | Conversions |
| Pattern Interrupt | TikTok/Reels | +${rand(30, 55)}% | Discovery |
| Contrarian | Twitter/LinkedIn | +${rand(20, 45)}% | Engagement |

## Delivery Tips
→ Deliver hook in first **${rand(2, 4)} seconds** — no intro music, no title cards
→ Match energy: high-energy hook + calm delivery = pattern interrupt
→ Add text overlay for the ${rand(55, 70)}% who watch silent
→ End the hook on a cliffhanger — never complete the thought immediately

---
*Generated by CreatorOS Viral Hooks Generator*`;
}

// ─── AI Video Editor ──────────────────────────────────────────────────────────
export function generateVideoEdit(concept: string, style: string, length: string): string {
  const c = concept || "your video concept";
  const mins = parseFloat(length) || 5;
  const cuts = Math.floor(mins * rand(6, 10));

  return `## AI Edit Plan — "${c}"

**Format:** ${style} · ${length} · ${cuts} estimated cuts
**Output quality:** ${pick(["4K 30fps", "1080p 60fps", "4K 60fps", "1080p 30fps"])} recommended

---

### PRE-EDIT CHECKLIST
☐ Footage organized by scene in timeline
☐ Backup copy of raw files confirmed
☐ Audio levels normalized to ${pick(["-14", "-16", "-12"])} LUFS
☐ Color temperature consistent across clips

---

### EDIT STRUCTURE (${mins}-minute video)

**[0:00 – 0:${Math.round(mins * 0.08 * 60).toString().padStart(2, "0")}] Cold open**
→ Start with the most visually interesting moment from the whole video
→ No title card yet — earn attention first
→ Cut pace: rapid (every 1–2 seconds)

**[0:${Math.round(mins * 0.08 * 60).toString().padStart(2, "0")} – 0:${Math.round(mins * 0.2 * 60).toString().padStart(2, "0")}] Hook + setup**
→ Introduce the premise of "${c}"
→ Use J-cut: audio from next scene bleeds in before visuals
→ Add tension with subtle music swell

**[0:${Math.round(mins * 0.2 * 60).toString().padStart(2, "0")} – ${Math.floor(mins * 0.7)}:${Math.round((mins * 0.7 % 1) * 60).toString().padStart(2, "0")}] Main content**
→ 3-act delivery: problem → framework → solution
→ B-roll every ${rand(20, 40)} seconds to maintain visual interest
→ Callout text for key stats/claims
→ Cut on action (not between actions)

**[${Math.floor(mins * 0.7)}:${Math.round((mins * 0.7 % 1) * 60).toString().padStart(2, "0")} – ${Math.floor(mins * 0.9)}:${Math.round((mins * 0.9 % 1) * 60).toString().padStart(2, "0")}] Resolution**
→ Payoff moment — deliver the promised result
→ Slow the cut pace: let the message land

**[${Math.floor(mins * 0.9)}:${Math.round((mins * 0.9 % 1) * 60).toString().padStart(2, "0")} – ${mins}:00] CTA**
→ Direct camera, energized delivery
→ Subscribe nudge + next video preview
→ End screen: ${rand(15, 20)} seconds

---

### CAPTION STYLE
→ Font: ${pick(["Helvetica Bold", "DM Sans Bold", "Inter Black", "Montserrat ExtraBold"])}
→ Position: Bottom third (not covering face)
→ Color: White with ${pick(["black drop shadow", "semi-transparent box", "subtle outline"])}
→ Size: Readable on mobile at arm's length

### MUSIC STRATEGY
- **Tone for ${c}:** ${pick(["Upbeat + inspiring", "Cinematic + tension", "Lo-fi + focused", "Electronic + energetic"])}
- **Volume:** -${rand(20, 30)}dB under voice-over  
- **Transition:** Fade out starts ${rand(3, 8)} seconds before end

### TRANSITIONS
→ Hard cuts: ${rand(60, 80)}% of edits
→ L/J cuts: ${rand(10, 20)}% — audio transitions
→ Zoom cuts: max ${rand(3, 6)} per video — use sparingly
→ Avoid: wipes, dissolves, star wipes — they age poorly

### COLOR GRADE PRESET
Base: ${pick(["Filmic Pro Mojo", "VSCO Film", "Cinematic Orange & Teal", "Clean + Warm", "High contrast dark"])}
→ Boost contrast +${rand(5, 15)}
→ Shadows: push ${pick(["blue/teal", "warm orange", "neutral"])}
→ Highlights: pull down ${rand(5, 20)}%
→ Skin tone: ensure correct white balance first

---
*Generated by CreatorOS AI Video Editor*`;
}

export function generateVideoChecklist(): string {
  return `## Export & Publish Checklist

### Before Export
☐ Watch full video once at 2× speed — catches timing issues
☐ Check audio on headphones AND phone speaker
☐ Review first 30 seconds — this determines retention
☐ Verify captions cover silent-watching use case
☐ Check thumbnail matches video content

### Export Settings
**YouTube:** H.264, 1080p or 4K, ${rand(10, 20)}Mbps, AAC 320kbps
**Instagram Reels:** MP4, 1080×1920, under 4GB, 30fps
**TikTok:** MP4, 1080×1920, under 500MB
**Twitter/X:** MP4, under 512MB, under ${rand(2, 3)} min 20s

### Publishing Timing
→ YouTube: Upload ${rand(12, 48)}h early, set scheduled publish
→ Instagram: Post natively (not 3rd party) for max reach
→ TikTok: Use original upload — re-uploads get reduced reach

*Generated by CreatorOS AI Video Editor*`;
}

// ─── Script Generator ─────────────────────────────────────────────────────────
export function generateScript(topic: string, type: string, length: string): string {
  const t = topic || "your topic";
  const lengthLabel = { Short: "5–7 min", Medium: "10–12 min", Long: "18–22 min" }[length] || "10 min";

  if (type === "Podcast") {
    return `## Podcast Script — "${t}" (${lengthLabel})

**Episode Number:** ${rand(1, 200)} · **Format:** Solo episode
**Target listener:** ${pick(["Aspiring creator", "Entrepreneur", "Content professional", "Digital marketer"])}

---

### COLD OPEN (0:00–1:00)
[Start mid-sentence or mid-thought — don't wait for music to finish]

"...and that's exactly the moment I realized everything I knew about ${t} was wrong.

But let me back up. [Pause] I want to tell you about a conversation I had with someone in my community last week that completely reframed how I think about this."

---

### INTRO / HOOK (1:00–2:00)
"Welcome back to [Show Name] — the show where we [show premise in one line].

I'm [Host Name], and today we're going deep on ${t}.

Here's what we're covering today:
→ Why most people get ${t} backwards
→ The framework I've seen work for ${fmt(rand(100, 1000))}+ creators
→ And the one thing I wish someone told me ${rand(2, 5)} years ago

This one's ${lengthLabel}. Grab your notes — let's go."

---

### SEGMENT 1: THE PROBLEM (2:00–${type === "Podcast" ? "6" : "4"}:00)
[Establish the core tension. Be specific.]

"Let's talk about why ${t} is so hard for most people.

It's not about effort — I want to be really clear about that. Most of the people struggling with ${t} are working incredibly hard. The problem is they're working hard on the wrong things.

Here's what I mean: [Insert personal story or case study with specific details]

The mistake is [specific misconception]. And look, I made this exact mistake for ${rand(6, 36)} months. It cost me [specific consequence].

What actually matters is [the reframe]."

---

### SEGMENT 2: THE FRAMEWORK (6:00–${type === "Podcast" ? "14" : "10"}:00)
"Okay, so let's get into the actual framework.

I call this [Framework Name]. It has ${rand(3, 5)} parts:

**Part 1: [Foundation]**
[Explain with an analogy. Make it tangible.]
"Think of it like [metaphor]. When you do [action], you get [result]."

**Part 2: [System]**
[This is the meat. Be specific, give examples.]
"In practice, this looks like: [specific example from real life or case study]"

**Part 3: [Scale]**
[The multiplier. What changes when this is working?]
"Once you have Parts 1 and 2 working, Part 3 is where the compounding kicks in."

---

### SEGMENT 3: MISTAKES + NUANCE (${type === "Podcast" ? "14" : "10"}:00–${type === "Podcast" ? "18" : "14"}:00)
"Before we wrap, I want to address the ${rand(2, 4)} things that trip people up even after they understand the framework.

Mistake 1: [Common pitfall]
The fix: [Specific correction]

Mistake 2: [Another pitfall]
The fix: [Specific correction]"

---

### CLOSE (last 1–2 min)
"So here's the thing about ${t} that I want you to walk away with today:

[One-sentence core message].

Start with [first action]. Not next week — this week. Even ${rand(10, 30)} minutes today changes the trajectory.

If this episode helped you, I'd love to hear your biggest takeaway. Send me a DM on [platform] or reply to this week's newsletter.

Thanks for listening to [Show Name]. I'll see you [next episode cadence].

[Outro music]"

---

### SHOW NOTES SUMMARY
- Episode title: "${t} — The Framework That Actually Works"
- Guest: Solo
- Resources mentioned: [list any tools, books, links]
- CTA: Follow + review on Apple Podcasts

---
*Generated by CreatorOS Script Generator*`;
  }

  if (type === "TikTok") {
    return `## TikTok Script — "${t}" (${rand(30, 60)} seconds)

**Hook score:** ${rand(88, 97)}/100 · **Format:** Face-to-camera + text overlay

---

### HOOK (0–3s) — THE EVERYTHING
[Speak immediately. No pause, no music intro]

> "${pick([
  `"Stop. You need to see this ${t} thing."`,
  `"${t} tip that literally changed my whole approach:"`,
  `"Nobody talks about this ${t} trick and I have no idea why."`,
  `"I tested ${t} every day for ${rand(7, 30)} days. Here's what happened:"`,
])}"

[Text overlay: "${t} hack 🔥" — top of screen]

---

### DELIVERY (3–45s) — RAPID FIRE
[New shot every ${rand(2, 4)} seconds. Keep energy HIGH.]

**Point 1 (3–12s):**
"[Core insight #1 — one sentence, maximum punch]"
[Text overlay: key phrase]

**Point 2 (12–25s):**
"[The surprising part — this is where you lean in to camera]"
[Quick cut — different angle or zoom]

**Point 3 (25–40s):**  
"[The actionable part — what they do RIGHT NOW]"
[Show don't tell if possible — screen recording or demo]

---

### CLOSE (40–60s) — HOOK THE NEXT WATCH
"[Deliver the payoff — the 'wow' moment]

If this helped — follow me. I post ${t} tips ${pick(["daily", "every week", "3× a week"])}.
Save this for later. 📌"

[Text overlay: "Follow for more ${t} tips"]

---

### PRODUCTION NOTES
→ Film in portrait (9:16), natural light from front
→ Cut on every sentence — no dead air
→ First frame: you already talking or in motion
→ Captions: auto-generate + review for accuracy

---
*Generated by CreatorOS Script Generator*`;
  }

  // YouTube default
  return `## YouTube Script — "${t}" (${lengthLabel})

**Predicted retention:** ${rand(55, 72)}% avg · **Search potential:** ${pick(["High", "Very High", "Moderate"])}

---

### HOOK (0:00–0:30) — 30-SECOND GAUNTLET
[The hook determines whether they watch the whole video. Don't rush it.]

"${pick([
  `Here's something that took me ${rand(1, 5)} years to figure out about ${t}:`,
  `Most tutorials about ${t} leave out the one thing that actually makes a difference.`,
  `I'm going to show you the ${t} approach that took me from [struggling] to [result].`,
])}

By the end of this video, you'll know exactly [specific deliverable]. And I'm going to show you with real examples — not theory."

---

### INTRO (0:30–1:00)
"[Your name], and on this channel I [channel premise in one sentence].

Today we're covering:
→ [Benefit 1]
→ [Benefit 2]  
→ [Benefit 3 — the most surprising one]

Let's get into it."

---

### MAIN CONTENT (1:00–${parseInt(lengthLabel) || 10}:30)

**Chapter 1 — Why Most People Get ${t} Wrong (1:00–${Math.round(mins * 0.3)}:00)**
"Before we talk about the solution, let's be honest about the problem.

[Explain the common mistake with empathy — been there yourself]

The reason this happens is [root cause]. And I see it constantly in [your community/comments/students]."

**Chapter 2 — The Framework (${Math.round(mins * 0.3)}:00–${Math.round(mins * 0.7)}:00)**
"Here's the approach that changed everything for me:

Step 1: [Action]
→ [Why this works]
→ [Specific example]

Step 2: [Action]
→ [Why this works]
→ [Specific example]

Step 3: [Action]
→ This is the step most people skip. [Explain why it matters]"

**Chapter 3 — Real Example (${Math.round(mins * 0.7)}:00–${Math.round(mins * 0.9)}:00)**
"Let me show you this in action. [Screen share or case study walkthrough]"

---

### CLOSE (last 30s)
"Here's the bottom line on ${t}:

[One powerful sentence summary].

Start with Step 1 today — not tomorrow, today. Even ${rand(10, 20)} minutes changes your trajectory.

If this video helped you, subscribe — new ${t} content every [cadence].
Drop a comment with your biggest takeaway — I read every single one.

See you in the next one."

---

### END SCREEN
- Link to related video: "[Related ${t} video]"
- Subscribe button: centered
- Playlist: Your ${t} playlist

---
*Generated by CreatorOS Script Generator*`;
}

const mins = 10;

// ─── AI Podcast Generator ─────────────────────────────────────────────────────
export function generatePodcast(topic: string, format: string, duration: string): string {
  const t = topic || "your topic";
  const guestName = pick(["Alex Chen", "Sarah Kim", "Marcus Johnson", "Priya Patel", "Jordan Lee"]);

  return `## Podcast Episode — "${t}"

**Format:** ${format} · **Duration:** ${duration}
**Episode #:** ${rand(1, 200)} · **Season:** ${rand(1, 5)}

---

### EPISODE OVERVIEW

**Title Options:**
1. "${t}: What Everyone Gets Wrong (And What Actually Works)"
2. "The ${t} Playbook: ${rand(3, 8)} Strategies for ${new Date().getFullYear()}"
3. "From ${rand(0, 1000)} to ${fmt(rand(10, 100) * 1000)}: A ${t} Story"

**Logline:**
"In this episode, ${format === "Interview" ? `we sit down with ${guestName} to unpack` : "we break down"} the real story behind ${t} — what the top creators know that most people don't, and the framework you can apply starting today."

---

### CHAPTER MARKERS

[00:00] Cold open / teaser quote
[01:30] Welcome + episode intro
[03:00] ${format === "Interview" ? `Guest intro — ${guestName}'s background` : "Context — why this topic now"}
[08:00] Main topic: Part 1 — The Problem
[16:00] Main topic: Part 2 — The Framework
[${format === "Interview" ? "26" : "22"}:00] ${format === "Interview" ? "Deep dive question" : "Advanced strategies"}
[${format === "Interview" ? "36" : "30"}:00] Mistakes to avoid
[${format === "Interview" ? "44" : "38"}:00] Rapid fire / quick wins
[${format === "Interview" ? "50" : "44"}:00] Where to go from here
[${format === "Interview" ? "53" : "47"}:00] Close + CTA

---

### SHOW NOTES (Full)

**Episode Summary**
This week ${format === "Interview" ? `we're joined by ${guestName}, an expert in ${t}, to discuss` : "we dive deep into"} everything you need to know about ${t} in ${new Date().getFullYear()}.

Key topics covered:
• Why most approaches to ${t} fail in the first ${rand(30, 90)} days
• The ${rand(3, 5)}-step framework for sustainable results
• Real case study: How one creator went from ${rand(0, 1000)} to ${fmt(rand(10, 100) * 1000)} using this exact method
• The ${rand(2, 3)} tools that make ${t} ${rand(3, 10)}× easier
• What's changing about ${t} in the next ${rand(6, 12)} months

**Resources Mentioned**
→ [Tool/book/resource #1] — [brief description]
→ [Tool/book/resource #2] — [brief description]
→ [Tool/book/resource #3] — [brief description]

${format === "Interview" ? `**Connect with ${guestName}:**\n→ Website: [link]\n→ Instagram: @[handle]\n→ Newsletter: [link]\n` : ""}
**Connect with the show:**
→ Instagram: @[yourshow]
→ Newsletter: [link to subscribe]
→ Leave a review: [Apple Podcasts link]

---

### INTRO SCRIPT (Word-for-Word)

[MUSIC FADE IN → FADE OUT over 15 seconds]

"Welcome back to [Show Name] — the show where we [show premise in one sentence].

I'm [Host], and today's episode is one I've been looking forward to for a while.

${format === "Interview"
  ? `We're talking with ${guestName} about ${t}. ${guestName} has [credential] and [credential], and their take on this topic is genuinely different from anything I've heard before.`
  : `We're going deep on ${t}. I've been thinking about this for ${rand(2, 8)} weeks, and I've pulled together everything I know into one episode.`}

If you're ${pick(["struggling with", "curious about", "trying to understand", "looking to improve your approach to"])} ${t} — you need to hear what we're about to cover.

Let's get into it."

---

### OUTRO SCRIPT

"Okay — that's a wrap on today's episode.

If you took one thing from this conversation, I hope it's [core message from episode].

${format === "Interview" ? `Huge thanks to ${guestName} for coming on — links to find them are in the show notes below.` : ""}

If you got value from this episode, the best thing you can do is share it with one person who needs to hear it. That's how the show grows, and it means the world to me.

I'll be back [cadence] with another episode. Until then — keep creating.

[OUTRO MUSIC]"

---

### PRODUCTION CHECKLIST
☐ Record intro/outro in a separate session (fresher energy)
☐ Normalize audio to -${rand(14, 16)} LUFS
☐ Remove filler words with Descript or Adobe Podcast
☐ Add chapter markers in metadata
☐ Write show notes before publishing
☐ Create audiogram for social media (${rand(30, 60)}-second clip)
☐ Send episode summary to newsletter list

---
*Generated by CreatorOS AI Podcast Generator*`;
}

// ─── Social Media Planner ─────────────────────────────────────────────────────
export function generatePlanner(niche: string, platforms: string[], frequency: string): string {
  const n = niche || "content creation";
  const p = platforms.length > 0 ? platforms.join(", ") : "Instagram, TikTok, YouTube";
  const freqNum = { "Daily": 7, "3×/week": 3, "5×/week": 5, "2×/week": 2 }[frequency] || 5;

  const formats = ["Reel", "Carousel", "Story", "Long-form", "Tutorial", "BTS", "Q&A", "Poll", "Collab", "Thread"];
  const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

  const weeks = [1, 2, 3, 4].map(w => {
    const postDays = days.slice(0, freqNum);
    const postsStr = postDays.map((d, i) => (
      `  ${d}: ${pick(formats)} — "${n} angle #${(w - 1) * freqNum + i + 1}: ${pick([
        "Educational tip", "Personal story", "Trending hook", "Tutorial breakdown",
        "Behind-the-scenes", "Quick win", "Community post", "Results reveal", "Myth bust",
      ])}"`
    )).join("\n");
    return `**Week ${w} — ${["Foundation", "Value Drop", "Engagement Push", "Monetization"][w - 1]}**\n${postsStr}`;
  });

  return `## 30-Day Content Calendar — ${n}

**Platforms:** ${p}
**Frequency:** ${frequency} (${freqNum * 4} posts/month)
**Estimated Reach:** ${fmt(rand(100, 800) * 1000)} per month

---

### MONTHLY THEME
"${pick([
  `Establishing ${n} authority`,
  `${n} myths vs reality`,
  `${n} results in 30 days`,
  `The ${n} beginner's roadmap`,
])}" — consistency around one core message builds identity faster than variety.

---

### WEEKLY BREAKDOWN

${weeks.join("\n\n")}

---

### CONTENT PILLARS (3 per niche)
**Pillar 1: Education (${rand(35, 45)}% of posts)**
→ How-tos, tutorials, tips, frameworks
→ Format: Carousels and long-form perform best
→ CTA: Save this / follow for more

**Pillar 2: Entertainment (${rand(25, 35)}% of posts)**
→ Relatable moments, humor, storytelling, personality
→ Format: Reels and TikToks perform best
→ CTA: Share this / tag someone

**Pillar 3: Inspiration (${rand(20, 30)}% of posts)**
→ Results, transformations, motivation, milestones
→ Format: Carousels and videos
→ CTA: Comment your goal / DM me

---

### OPTIMAL POSTING TIMES

| Platform | Best Days | Best Time |
|----------|-----------|-----------|
| Instagram | Tue, Thu, Sat | 6–8pm local |
| TikTok | Daily | 7–9pm local |
| YouTube | Thu, Sat | 2–4pm EST |
| LinkedIn | Tue, Wed, Thu | 8–10am local |
| Twitter/X | Weekdays | 8am + 6pm |

---

### ENGAGEMENT STRATEGY
**First ${rand(30, 60)} minutes after posting:**
→ Reply to every comment (triggers notification to commenter)
→ Engage with ${rand(10, 20)} accounts in your niche
→ Story repost with "new post" sticker

**Weekly:**
→ ${rand(1, 2)}× live stream or Q&A story
→ Poll or quiz story (${rand(20, 40)}% engagement rate avg)
→ DM first ${rand(5, 15)} new followers with a welcome message

---

### CONTENT BATCHING SCHEDULE
| Day | Activity |
|-----|----------|
| Monday | Plan and script week's content |
| Tuesday | Film all video content |
| Wednesday | Edit + caption writing |
| Thursday | Schedule + design graphics |
| Friday | Engage + analyze last week |

---

### MONTH-END METRICS TO TRACK
☐ Total followers gained: ____
☐ Top performing post: ____
☐ Best posting time: ____
☐ Average reach per post: ____
☐ Profile visits: ____
☐ Link-in-bio clicks: ____

---
*Generated by CreatorOS Social Media Planner*`;
}

export function generatePlannerCalendar(niche: string, frequency: string): string {
  const n = niche || "content";
  const formats = ["Reel 📱", "Carousel 🖼️", "Story ⭕", "Long-form 🎥", "Thread 🧵", "Tutorial 📚"];
  const weeks = 4;
  const postsPerWeek = { Daily: 7, "3×/week": 3, "5×/week": 5, "2×/week": 2 }[frequency] || 5;
  const lines: string[] = [];

  lines.push(`## Visual Content Calendar — ${n}\n`);
  for (let w = 1; w <= weeks; w++) {
    lines.push(`### Week ${w}`);
    lines.push(`| Day | Format | Topic | Status |`);
    lines.push(`|-----|--------|-------|--------|`);
    const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].slice(0, postsPerWeek);
    days.forEach(d => {
      lines.push(`| ${d} | ${pick(formats)} | ${n} content ${rand(1, 99)} | ⬜ Planned |`);
    });
    lines.push("");
  }

  lines.push(`\n*Generated by CreatorOS Social Media Planner*`);
  return lines.join("\n");
}
